### ISSUE TITLE
Opnieuw gulp aanmaken

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Frontend#4]
@ExCellRaD jij begint opnieuw en vergeet niet om een `.travis.yaml` fila aan met deze code: 

```yml
language: node_js
node_js:
  - "6.9"
before_script:
  - npm install
  - npm install -g gulp
script: 
  - gulp sass
  - gulp css
  - gulp html-validate
  - gulp js
  - gulp
```

https://gist.github.com/HeinPauwelyn/3ea09bee5c41152e16d5e250b1a39985

Vergeet niet om alle installaties te doen bij de `before_script`!
